version: "2.1"

services:
  scandai:
    image: paolini/scandai
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - backend

  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
