name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install node packages
      run: npm ci
    - name: Build Js bundle
      run: npm run build
    - name: Extract version number
      run: echo VERSION=$( node -e 'console.log(require("./package.json").version)' ) >> $GITHUB_ENV
    - name: Test version number
      run: echo ${{ env.VERSION }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: paolini/scandai
        tags: |
          type=ref,event=tag
          type=ref,event=branch
          type=semver,pattern={{version}}
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        push: true
        context: .
        tags: paolini/scandai:${{ env.VERSION }}
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
